/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_andrivertest_PrinterInterface */

#ifndef _Included_com_example_andrivertest_PrinterInterface
#define _Included_com_example_andrivertest_PrinterInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_andrivertest_PrinterInterface
 * Method:    PrintInit
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jboolean JNICALL Java_com_example_andrivertest_PrinterInterface_PrintInit
  (JNIEnv *, jobject);

/*
 * Class:     com_example_andrivertest_PGetLastErrorCode
 * Method:    PGetLastErrorCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_example_andrivertest_PrinterInterface_PGetLastErrorCode
        (JNIEnv *, jobject);

/*
 * Class:     com_example_andrivertest_PrinterInterface
 * Method:    SetCutMode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jboolean JNICALL Java_com_example_andrivertest_PrinterInterface_SetCutMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_andrivertest_PrinterInterface
 * Method:    SetAllcutOrHalfcut
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_andrivertest_PrinterInterface_SetAllcutOrHalfcut
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_andrivertest_PrinterInterface
 * Method:    PrintSample
 * Signature: (I)I
 */
JNIEXPORT jboolean JNICALL Java_com_example_andrivertest_PrinterInterface_PrintSample
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_andrivertest_PrinterInterface
 * Method:    PrintAllString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jboolean JNICALL Java_com_example_andrivertest_PrinterInterface_PrintAllString
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_andrivertest_PrinterInterface
 * Method:    PrintImage
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jboolean JNICALL Java_com_example_andrivertest_PrinterInterface_PrintImage
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_andrivertest_PrinterInterface
 * Method:    PrintBlackBarcode
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT bool JNICALL Java_com_example_andrivertest_PrinterInterface_PrintBlackBarcode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_andrivertest_PrinterInterface
 * Method:    PrintCodePaper
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_andrivertest_PrinterInterface_PrintCodePaper
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_andrivertest_PrinterInterface
 * Method:    PrintContinue
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_andrivertest_PrinterInterface_PrintContinue
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_andrivertest_PrinterInterface
 * Method:    PrintPaperMode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT bool JNICALL Java_com_example_andrivertest_PrinterInterface_PrintPaperMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_andrivertest_PrinterInterface
 * Method:    PrintSpeedTest
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_andrivertest_PrinterInterface_PrintSpeedTest
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_andrivertest_PrinterInterface
 * Method:    PrintCutPaperSpeed
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_andrivertest_PrinterInterface_PrintCutPaperSpeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_andrivertest_PrinterInterface
 * Method:    PrintBarCode
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_andrivertest_PrinterInterface_PrintBarCode
  (JNIEnv *, jobject, jint, jint);


JNIEXPORT jstring JNICALL Java_com_example_andrivertest_PrinterInterface_GetLastErrStr
        (JNIEnv *, jobject);

JNIEXPORT bool JNICALL Java_com_example_andrivertest_PrinterInterface_PrintString
        (JNIEnv *, jobject , jstring);

JNIEXPORT bool JNICALL Java_com_example_andrivertest_PrinterInterface_CutPaper
        (JNIEnv *, jobject);

JNIEXPORT bool JNICALL Java_com_example_andrivertest_PrinterInterface_PSetPageMode
        (JNIEnv *, jobject, jint ,jint, jint, jint);

JNIEXPORT jstring JNICALL Java_com_example_andrivertest_PrinterInterface_GetPrintHwInfo
        (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_example_andrivertest_PrinterInterface_PrinterStatus
        (JNIEnv *, jobject);

JNIEXPORT jboolean JNICALL Java_com_example_andrivertest_PrinterInterface_GetAuthority
        (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_example_andrivertest_PrinterInterface_GetPDFCode
        (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_example_andrivertest_PrinterInterface_GetLastErrCode
        (JNIEnv *, jobject);


JNIEXPORT jint JNICALL Java_com_example_andrivertest_PrinterInterface_PInit
        (JNIEnv *, jobject, jstring ,jstring);





#ifdef __cplusplus
}
#endif
#endif
